### ISSUE TITLE
Chamar palestrante para o tema "Autômatos Celulares e simulações"

### ISSUE THREAD

**Issue by JPTIZ** [seccom-ufsc/2020#4]
Em homenagem a John Conway, seria interessante trazermos alguém (possivelmente da matemática) para palestrar sobre o tema.

**Comment by Coquinho** [comment]
Pq especificamente da matématica?

**Comment by JPTIZ** [comment]
> Pq especificamente da matématica?

John Conway era matemático, então _imagino_ que possa ter alguém de lá que gostaria bastante de falar sobre ele.

**Comment by Coquinho** [comment]
haha, justo eu acho, talvez na fisíca tb encontrem alguem. Talvez até aqui em CCO mesmo tb tenha, mas é sempre bom ter gente de fora do departamento/CTC realmente.
